import type { Metadata } from 'next'
import { Inter } from 'next/font/google';
import "react-multi-carousel/lib/styles.css";
import 'bootstrap/dist/css/bootstrap.min.css';

import './globals.css';

// import Carousel from 'react-bootstrap/Carousel';
// import LargQuiztoferLogo from '@/../public/images/Quiztofer_Logo_Larg.png';
// import UncontrolledExample from '@/components/carousel';
import QuiztoferHeader from '@/components/QuiztoferHeader';
import { useState } from 'react';
import SideMenuBar from '@/components/sideMenuBar';



const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Quiz-tofer',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  // console.log('Layout');
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" type="text/css" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css"  />
      </head>
      <body className={inter.className}>
      <SideMenuBar />
        <div className='container'>
          <div className='row justify-content-md-center'>
            <QuiztoferHeader />
          </div>
          <div className='row'>
            <hr />
          </div>
          
          {children}
          
        </div>

        
      </body>
    </html>
  )
}
